apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: userprofile-blue-green
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Harishporwal18/Shine-GitOps-Project.git
    targetRevision: main
    path: Retail-chart
    helm:
      values: |
        userprofile:
          activeVersion: blue
  destination:
    server: harish-test-cluster-dns-6obcku6o.hcp.eastus.azmk8s.io
    namespace: retail
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
